# Generated by Django 5.0.4 on 2024-06-16 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="emai",
            new_name="email",
        ),
    ]
